In [1]:
!pip install yfinance

Requirement already satisfied: yfinance in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (1.2.0)
Requirement already satisfied: pandas>=1.3.0 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (3.0.1)
Requirement already satisfied: numpy>=1.16.5 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (2.4.3)
Requirement already satisfied: requests>=2.31 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (2.32.5)
Requirement already satisfied: multitasking>=0.0.7 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (4.9.4)
Requirement already satisfied: pytz>=2022.5 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (2026.1.post1)
Requirement already satisfied: frozendict>=2.3.4 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (4.0.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (4.14.3)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (7.34.1)
Requirement already satisfied: websockets>=13.0 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (16.0)
Requirement already satisfied: cffi>=1.12.0 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2026.2.25)
Requirement already satisfied: soupsieve>=1.6.1 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: pycparser in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.6.3)

In [6]:
import yfinance as yf
data=yf.download('RELIANCE.NS',period='1y',multi_level_index=False)
data

[*********************100%***********************]  1 of 1 completed

                  Close         High          Low         Open    Volume
Date
2025-04-02  1246.172974  1250.555495  1238.951814  1242.587319  10142590
2025-04-03  1243.732666  1246.820432  1228.145018  1228.145018   7434366
2025-04-04  1199.907593  1240.495487  1188.403612  1236.162816  17908652
2025-04-07  1161.062744  1166.590715  1110.415052  1127.696009  22156106
2025-04-08  1177.497192  1191.839934  1158.672473  1167.337816  19555040
...                 ...          ...          ...          ...       ...
2026-03-25  1413.099976  1430.500000  1408.400024  1420.000000  19041331
2026-03-27  1348.099976  1404.699951  1345.000000  1401.000000  23266517
2026-03-30  1343.900024  1365.000000  1334.099976  1335.000000  24393861
2026-04-01  1369.199951  1384.400024  1362.900024  1384.199951  14404619
2026-04-02  1350.500000  1358.199951  1328.000000  1357.000000  21280051

[248 rows x 5 columns]

In [9]:
data=yf.download('EURUSD=X',period='1y',interval='1h',multi_level_index=False,ignore_tz=True)
data

[*********************100%***********************]  1 of 1 completed

                        Close      High       Low      Open  Volume
Datetime
2025-04-04 00:00:00  1.104728  1.106684  1.104606  1.106684       0
2025-04-04 01:00:00  1.106317  1.106562  1.103997  1.104972       0
2025-04-04 02:00:00  1.107052  1.107420  1.106072  1.106439       0
2025-04-04 03:00:00  1.106684  1.108279  1.106439  1.107052       0
2025-04-04 04:00:00  1.109632  1.110001  1.106195  1.106684       0
...                       ...       ...       ...       ...     ...
2026-04-03 18:00:00  1.152206  1.152472  1.152074  1.152206       0
2026-04-03 19:00:00  1.151808  1.152339  1.151676  1.152339       0
2026-04-03 20:00:00  1.151941  1.152074  1.151808  1.151808       0
2026-04-03 21:00:00  1.152206  1.153270  1.151808  1.151941       0
2026-04-03 22:00:00  1.152206  1.152339  1.152206  1.152339       0

[6148 rows x 5 columns]

In [13]:
data=yf.download('AMZN',start='2025-01-01',end='2025-12-31',interval='1h',multi_level_index=False,ignore_tz=True)
data

[*********************100%***********************]  1 of 1 completed

                          Close        High         Low        Open   Volume
Datetime
2025-01-02 09:30:00  223.253906  225.149994  220.610001  222.844803  9676135
2025-01-02 10:30:00  222.981598  223.350006  221.710297  223.250000  3822526
2025-01-02 11:30:00  220.809998  223.929993  220.729996  222.964996  2941425
2025-01-02 12:30:00  219.500000  220.859894  218.190002  220.859894  3981065
2025-01-02 13:30:00  219.850006  219.990005  218.570007  219.490005  2351314
...                         ...         ...         ...         ...      ...
2025-12-30 11:30:00  231.294998  231.960007  231.100006  231.850006  1194488
2025-12-30 12:30:00  231.195694  231.459000  231.059601  231.279999  1106057
2025-12-30 13:30:00  231.699905  231.860001  231.080093  231.179993  1537866
2025-12-30 14:30:00  231.740005  231.800003  231.229996  231.699997  1443287
2025-12-30 15:30:00  232.489899  232.770004  231.750000  231.750000  2410712

[1731 rows x 5 columns]