In [2]:
!pip install yfinance

Requirement already satisfied: yfinance in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (1.2.0)
Requirement already satisfied: pandas>=1.3.0 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (3.0.1)
Requirement already satisfied: numpy>=1.16.5 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (2.4.3)
Requirement already satisfied: requests>=2.31 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (2.32.5)
Requirement already satisfied: multitasking>=0.0.7 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (4.9.4)
Requirement already satisfied: pytz>=2022.5 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (2026.1.post1)
Requirement already satisfied: frozendict>=2.3.4 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (4.0.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (4.14.3)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (7.34.1)
Requirement already satisfied: websockets>=13.0 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from yfinance) (16.0)
Requirement already satisfied: cffi>=1.12.0 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2026.2.25)
Requirement already satisfied: soupsieve>=1.6.1 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: pycparser in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.6.3)

In [3]:
import yfinance as yf
data=yf.download('RELIANCE.NS',period='1y',multi_level_index=False)
data

[*********************100%***********************]  1 of 1 completed

                  Close         High          Low         Open    Volume
Date
2025-04-02  1246.172974  1250.555495  1238.951814  1242.587319  10142590
2025-04-03  1243.732666  1246.820432  1228.145018  1228.145018   7434366
2025-04-04  1199.907593  1240.495487  1188.403612  1236.162816  17908652
2025-04-07  1161.062744  1166.590715  1110.415052  1127.696009  22156106
2025-04-08  1177.497192  1191.839934  1158.672473  1167.337816  19555040
...                 ...          ...          ...          ...       ...
2026-03-25  1413.099976  1430.500000  1408.400024  1420.000000  19041331
2026-03-27  1348.099976  1404.699951  1345.000000  1401.000000  23266517
2026-03-30  1343.900024  1365.000000  1334.099976  1335.000000  24393861
2026-04-01  1369.199951  1384.400024  1362.900024  1384.199951  14404619
2026-04-02  1350.500000  1358.199951  1328.000000  1357.000000  21280051

[248 rows x 5 columns]

In [4]:
data=yf.download('EURUSD=X',period='1y',interval='1h',multi_level_index=False,ignore_tz=True)
data

[*********************100%***********************]  1 of 1 completed

                        Close      High       Low      Open  Volume
Datetime
2025-04-04 00:00:00  1.104728  1.106684  1.104606  1.106684       0
2025-04-04 01:00:00  1.106317  1.106562  1.103997  1.104972       0
2025-04-04 02:00:00  1.107052  1.107420  1.106072  1.106439       0
2025-04-04 03:00:00  1.106684  1.108279  1.106439  1.107052       0
2025-04-04 04:00:00  1.109632  1.110001  1.106195  1.106684       0
...                       ...       ...       ...       ...     ...
2026-04-03 18:00:00  1.152206  1.152472  1.152074  1.152206       0
2026-04-03 19:00:00  1.151808  1.152339  1.151676  1.152339       0
2026-04-03 20:00:00  1.151941  1.152074  1.151808  1.151808       0
2026-04-03 21:00:00  1.152206  1.153270  1.151808  1.151941       0
2026-04-03 22:00:00  1.152206  1.152339  1.152206  1.152339       0

[6148 rows x 5 columns]

In [5]:
data=yf.download('AMZN',start='2025-01-01',end='2025-12-31',interval='1h',multi_level_index=False,ignore_tz=True)
data

[*********************100%***********************]  1 of 1 completed

                          Close        High         Low        Open   Volume
Datetime
2025-01-02 09:30:00  223.253906  225.149994  220.610001  222.844803  9676135
2025-01-02 10:30:00  222.981598  223.350006  221.710297  223.250000  3822526
2025-01-02 11:30:00  220.809998  223.929993  220.729996  222.964996  2941425
2025-01-02 12:30:00  219.500000  220.859894  218.190002  220.859894  3981065
2025-01-02 13:30:00  219.850006  219.990005  218.570007  219.490005  2351314
...                         ...         ...         ...         ...      ...
2025-12-30 11:30:00  231.294998  231.960007  231.100006  231.850006  1194488
2025-12-30 12:30:00  231.195694  231.459000  231.059601  231.279999  1106057
2025-12-30 13:30:00  231.699905  231.860001  231.080093  231.179993  1537866
2025-12-30 14:30:00  231.740005  231.800003  231.229996  231.699997  1443287
2025-12-30 15:30:00  232.489899  232.770004  231.750000  231.750000  2410712

[1731 rows x 5 columns]

In [6]:
import datetime as dt
dt1=dt.datetime(2026,3,28)
dt2=dt.datetime(2026,4,4)
data=yf.download('AMZN',start=dt1,end=dt2,interval='1m',multi_level_index=False,ignore_tz=True)
data

[*********************100%***********************]  1 of 1 completed

                          Close        High         Low        Open   Volume
Datetime
2026-03-30 09:30:00  201.119995  201.569901  200.679993  201.350006  1852737
2026-03-30 09:31:00  201.570007  201.649994  201.110001  201.119995   188127
2026-03-30 09:32:00  201.916107  201.949997  201.430099  201.520004   198919
2026-03-30 09:33:00  201.889999  202.160004  201.610001  201.899994   162598
2026-03-30 09:34:00  201.820007  201.979996  201.669998  201.889999   177714
...                         ...         ...         ...         ...      ...
2026-04-02 15:55:00  209.710007  209.904999  209.524994  209.539993   223726
2026-04-02 15:56:00  209.699997  209.750000  209.619995  209.729904   173266
2026-04-02 15:57:00  209.710007  209.729996  209.580002  209.699997   182976
2026-04-02 15:58:00  209.699997  209.809998  209.699997  209.710007   274502
2026-04-02 15:59:00  209.770004  209.809998  209.600006  209.710007   594868

[1560 rows x 5 columns]

In [7]:
t1=yf.Ticker('AMZN')
t1.info

{'address1': '410 Terry Avenue North',
 'city': 'Seattle',
 'state': 'WA',
 'zip': '98109-5210',
 'country': 'United States',
 'phone': '206 266 1000',
 'website': 'https://www.amazon.com',
 'industry': 'Internet Retail',
 'industryKey': 'internet-retail',
 'industryDisp': 'Internet Retail',
 'sector': 'Consumer Cyclical',
 'sectorKey': 'consumer-cyclical',
 'sectorDisp': 'Consumer Cyclical',
 'longBusinessSummary': "Amazon.com, Inc. engages in the retail sale of consumer products, advertising, and subscriptions service through online and physical stores in North America and internationally. The company operates through three segments: North America, International, and Amazon Web Services (AWS). It also manufactures and sells electronic devices, including Kindle, fire tablets, fire TVs, echo, ring, blink, and eero; and develops and produces media content. In addition, the company offers programs that enable sellers to sell their products in its stores; and programs that allow authors, independent publishers, musicians, filmmakers, Twitch streamers, skill and app developers, and others to publish and sell content. Further, it provides compute, storage, Artificial intelligence, database, analytics, machine learning, and other services, as well as advertising services through programs, such as sponsored ads, display, and video advertising. Additionally, the company offers Amazon Prime, a membership program. The company's products offered through its stores include merchandise and content purchased for resale and products offered by third-party sellers. It serves consumers, sellers, developers, enterprises, content creators, advertisers, and employees. The company was incorporated in 1994 and is headquartered in Seattle, Washington.",
 'fullTimeEmployees': 1576000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Jeffrey P. Bezos',
   'age': 61,
   'title': 'Founder & Executive Chairman',
   'yearBorn': 1964,
   'fiscalYear': 2024,
   'totalPay': 1681840,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Andrew R. Jassy',
   'age': 57,
   'title': 'President, CEO & Director',
   'yearBorn': 1968,
   'fiscalYear': 2024,
   'totalPay': 1596889,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Brian T. Olsavsky',
   'age': 61,
   'title': 'Senior VP & CFO',
   'yearBorn': 1964,
   'fiscalYear': 2024,
   'totalPay': 371900,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. David A. Zapolsky J.D.',
   'age': 61,
   'title': 'Senior VP and Chief Global Affairs & Legal Officer',
   'yearBorn': 1964,
   'fiscalYear': 2024,
   'totalPay': 371900,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Douglas J. Herrington',
   'age': 58,
   'title': 'Chief Executive Officer of Worldwide Amazon Stores',
   'yearBorn': 1967,
   'fiscalYear': 2024,
   'totalPay': 386435,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Matthew S. Garman',
   'age': 48,
   'title': 'Chief Executive Officer of Amazon Web Series',
   'yearBorn': 1977,
   'fiscalYear': 2024,
   'totalPay': 384275,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Shelley L. Reynolds',
   'age': 60,
   'title': 'VP, Worldwide Controller & Principal Accounting Officer',
   'yearBorn': 1965,
   'fiscalYear': 2024,
   'totalPay': 163200,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Dr. Werner  Vogels',
   'title': 'Chief Technology Officer',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Dave  Fildes',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Drew  Herdener',
   'title': 'Senior Vice President of Communications & Corporate Responsibility',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 8,
 'compensationRisk': 10,
 'shareHolderRightsRisk': 3,
 'overallRisk': 9,
 'governanceEpochDate': 1775001600,
 'compensationAsOfEpochDate': 1735603200,
 'irWebsite': 'http://phx.corporate-ir.net/phoenix.zhtml?c=97664&p=irol-irhome',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 210.57,
 'open': 206.55,
 'dayLow': 204.9,
 'dayHigh': 212.2125,
 'regularMarketPreviousClose': 210.57,
 'regularMarketOpen': 206.55,
 'regularMarketDayLow': 204.9,
 'regularMarketDayHigh': 212.2125,
 'payoutRatio': 0.0,
 'beta': 1.383,
 'trailingPE': 29.256624,
 'forwardPE': 22.332802,
 'volume': 30069843,
 'regularMarketVolume': 30069843,
 'averageVolume': 50654972,
 'averageVolume10days': 46472030,
 'averageDailyVolume10Day': 46472030,
 'bid': 209.33,
 'ask': 209.76,
 'bidSize': 1,
 'askSize': 1,
 'marketCap': 2251864408064,
 'nonDilutedMarketCap': 2251864350899,
 'fiftyTwoWeekLow': 161.38,
 'fiftyTwoWeekHigh': 258.6,
 'allTimeHigh': 258.6,
 'allTimeLow': 0.065625,
 'priceToSalesTrailing12Months': 3.1410086,
 'fiftyDayAverage': 214.998,
 'twoHundredDayAverage': 224.5496,
 'trailingAnnualDividendRate': 0.0,
 'trailingAnnualDividendYield': 0.0,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 2307382312960,
 'profitMargins': 0.108339995,
 'floatShares': 9754500547,
 'sharesOutstanding': 10734920870,
 'sharesShort': 84784941,
 'sharesShortPriorMonth': 86971840,
 'sharesShortPreviousMonthDate': 1770940800,
 'dateShortInterest': 1773360000,
 'sharesPercentSharesOut': 0.007900001,
 'heldPercentInsiders': 0.09085,
 'heldPercentInstitutions': 0.67252,
 'shortRatio': 1.82,
 'shortPercentOfFloat': 0.0087,
 'impliedSharesOutstanding': 10734920870,
 'bookValue': 38.306,
 'priceToBook': 5.476166,
 'lastFiscalYearEnd': 1767139200,
 'nextFiscalYearEnd': 1798675200,
 'mostRecentQuarter': 1767139200,
 'earningsQuarterlyGrowth': 0.059,
 'netIncomeToCommon': 77669998592,
 'trailingEps': 7.17,
 'forwardEps': 9.39291,
 'lastSplitFactor': '20:1',
 'lastSplitDate': 1654473600,
 'enterpriseToRevenue': 3.218,
 'enterpriseToEbitda': 15.833,
 '52WeekChange': 0.1969074,
 'SandP52WeekChange': 0.30034864,
 'quoteType': 'EQUITY',
 'currentPrice': 209.77,
 'targetHighPrice': 360.0,
 'targetLowPrice': 175.0,
 'targetMeanPrice': 281.27344,
 'targetMedianPrice': 285.0,
 'recommendationMean': 1.33824,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 64,
 'totalCash': 123028996096,
 'totalCashPerShare': 11.461,
 'ebitda': 145730994176,
 'totalDebt': 178546999296,
 'quickRatio': 0.844,
 'currentRatio': 1.051,
 'totalRevenue': 716923994112,
 'debtToEquity': 43.435,
 'revenuePerShare': 67.279,
 'returnOnAssets': 0.06928,
 'returnOnEquity': 0.22286,
 'grossProfits': 360509997056,
 'freeCashflow': 23793125376,
 'operatingCashflow': 139514003456,
 'earningsGrowth': 0.05,
 'revenueGrowth': 0.136,
 'grossMargins': 0.50286,
 'ebitdaMargins': 0.20327,
 'operatingMargins': 0.10533,
 'financialCurrency': 'USD',
 'symbol': 'AMZN',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'marketState': 'CLOSED',
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.3 - Strong Buy',
 'cryptoTradeable': False,
 'postMarketChangePercent': 0.004764507,
 'postMarketPrice': 209.78,
 'postMarketChange': 0.009994507,
 'regularMarketChange': -0.800003,
 'regularMarketDayRange': '204.9 - 212.2125',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 50654972,
 'fiftyTwoWeekLowChange': 48.39,
 'fiftyTwoWeekLowChangePercent': 0.29985127,
 'fiftyTwoWeekRange': '161.38 - 258.6',
 'fiftyTwoWeekHighChange': -48.83,
 'fiftyTwoWeekHighChangePercent': -0.18882445,
 'fiftyTwoWeekChangePercent': 19.69074,
 'earningsTimestamp': 1770325200,
 'earningsTimestampStart': 1777579200,
 'earningsTimestampEnd': 1777579200,
 'earningsCallTimestampStart': 1770328800,
 'earningsCallTimestampEnd': 1770328800,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 7.17,
 'epsForward': 9.39291,
 'epsCurrentYear': 7.74541,
 'priceEpsCurrentYear': 27.083138,
 'fiftyDayAverageChange': -5.227997,
 'fiftyDayAverageChangePercent': -0.02431649,
 'twoHundredDayAverageChange': -14.779602,
 'twoHundredDayAverageChangePercent': -0.065818876,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_18749',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChangePercent': -0.379923,
 'regularMarketPrice': 209.77,
 'shortName': 'Amazon.com, Inc.',
 'longName': 'Amazon.com, Inc.',
 'corporateActions': [],
 'postMarketTime': 1775174397,
 'regularMarketTime': 1775160001,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 863703000000,
 'displayName': 'Amazon.com',
 'trailingPegRatio': 1.6126}

In [14]:
t1.get_balance_sheet()

,2025-12-31,2024-12-31,2023-12-31,2022-12-31,2021-12-31
TreasurySharesNumber,5.150000e+08,5.150000e+08,5.150000e+08,5.150000e+08,NaN
OrdinarySharesNumber,1.073100e+10,1.059300e+10,1.038300e+10,1.024200e+10,NaN
ShareIssued,1.124600e+10,1.110800e+10,1.089800e+10,1.075700e+10,NaN
NetDebt,NaN,NaN,NaN,1.326200e+10,1.252400e+10
TotalDebt,1.529870e+11,1.309000e+11,1.356110e+11,1.401180e+11,NaN
...,...,...,...,...,...
AllowanceForDoubtfulAccountsReceivable,-2.400000e+09,-2.000000e+09,-1.700000e+09,-1.400000e+09,NaN
GrossAccountsReceivable,7.012900e+10,5.745100e+10,5.395300e+10,4.376000e+10,NaN
CashCashEquivalentsAndShortTermInvestments,1.230290e+11,1.012020e+11,8.678000e+10,7.002600e+10,NaN
OtherShortTermInvestments,3.621900e+10,2.242300e+10,1.339300e+10,1.613800e+10,NaN
CashAndCashEquivalents,8.681000e+10,7.877900e+10,7.338700e+10,5.388800e+10,NaN

In [9]:
t1.get_cash_flow()

,2025-12-31,2024-12-31,2023-12-31,2022-12-31,2021-12-31
FreeCashFlow,7.695000e+09,3.287800e+10,3.221700e+10,-1.689300e+10,NaN
RepurchaseOfCapitalStock,NaN,0.000000e+00,0.000000e+00,-6.000000e+09,0.0
RepaymentOfDebt,-1.533200e+10,-1.695400e+10,-3.400800e+10,-4.700100e+10,NaN
IssuanceOfDebt,2.499300e+10,5.142000e+09,1.812900e+10,6.271900e+10,NaN
CapitalExpenditure,-1.318190e+11,-8.299900e+10,-5.272900e+10,-6.364500e+10,NaN
InterestPaidSupplementalData,1.949000e+09,2.364000e+09,3.112000e+09,2.142000e+09,NaN
IncomeTaxPaidSupplementalData,8.295000e+09,1.230800e+10,1.117900e+10,6.035000e+09,NaN
EndCashPosition,9.010600e+10,8.231200e+10,7.389000e+10,5.425300e+10,NaN
BeginningCashPosition,8.231200e+10,7.389000e+10,5.425300e+10,3.647700e+10,NaN
EffectOfExchangeRateChanges,1.164000e+09,-1.301000e+09,4.030000e+08,-1.093000e+09,NaN
ChangesInCash,6.630000e+09,9.723000e+09,1.923400e+10,1.886900e+10,NaN
FinancingCashFlow,9.661000e+09,-1.181200e+10,-1.587900e+10,9.718000e+09,NaN
CashFlowFromContinuingFinancingActivities,9.661000e+09,-1.181200e+10,-1.587900e+10,9.718000e+09,NaN
NetOtherFinancingCharges,NaN,NaN,-2.710000e+08,-2.480000e+08,-162000000.0
NetCommonStockIssuance,NaN,0.000000e+00,0.000000e+00,-6.000000e+09,0.0
CommonStockPayments,NaN,0.000000e+00,0.000000e+00,-6.000000e+09,0.0
NetIssuancePaymentsOfDebt,9.661000e+09,-1.181200e+10,-1.587900e+10,1.571800e+10,NaN
NetShortTermDebtIssuance,8.940000e+08,8.200000e+07,-7.548000e+09,3.999000e+09,NaN
ShortTermDebtPayments,-8.426000e+09,-5.060000e+09,-2.567700e+10,-3.755400e+10,NaN
ShortTermDebtIssuance,9.320000e+09,5.142000e+09,1.812900e+10,4.155300e+10,NaN
NetLongTermDebtIssuance,8.767000e+09,-1.189400e+10,-8.331000e+09,1.171900e+10,NaN
LongTermDebtPayments,-6.906000e+09,-1.189400e+10,-8.331000e+09,-9.447000e+09,NaN
LongTermDebtIssuance,1.567300e+10,0.000000e+00,0.000000e+00,2.116600e+10,NaN
InvestingCashFlow,-1.425450e+11,-9.434200e+10,-4.983300e+10,-3.760100e+10,NaN
CashFlowFromContinuingInvestingActivities,-1.425450e+11,-9.434200e+10,-4.983300e+10,-3.760100e+10,NaN
NetInvestmentPurchaseAndSale,-1.038400e+10,-9.602000e+09,4.139000e+09,2.903600e+10,NaN
SaleOfInvestment,4.438600e+10,1.640300e+10,5.627000e+09,3.160100e+10,NaN
PurchaseOfInvestment,-5.477000e+10,-2.600500e+10,-1.488000e+09,-2.565000e+09,NaN
NetBusinessPurchaseAndSale,-3.841000e+09,-7.082000e+09,-5.839000e+09,-8.316000e+09,NaN
PurchaseOfBusiness,-3.841000e+09,-7.082000e+09,-5.839000e+09,-8.316000e+09,NaN
NetPPEPurchaseAndSale,-1.283200e+11,-7.765800e+10,-4.813300e+10,-5.832100e+10,NaN
SaleOfPPE,3.499000e+09,5.341000e+09,4.596000e+09,5.324000e+09,NaN
PurchaseOfPPE,-1.318190e+11,-8.299900e+10,-5.272900e+10,-6.364500e+10,NaN
OperatingCashFlow,1.395140e+11,1.158770e+11,8.494600e+10,4.675200e+10,NaN
CashFlowFromContinuingOperatingActivities,1.395140e+11,1.158770e+11,8.494600e+10,4.675200e+10,NaN
ChangeInWorkingCapital,-1.996900e+10,-1.554100e+10,-1.154100e+10,-2.088600e+10,NaN
ChangeInOtherWorkingCapital,-2.140000e+08,4.007000e+09,4.578000e+09,2.216000e+09,NaN
ChangeInOtherCurrentAssets,-1.563200e+10,-1.448300e+10,-1.226500e+10,-1.327500e+10,NaN
ChangeInPayablesAndAccruedExpense,6.212000e+09,6.800000e+07,3.045000e+09,1.387000e+09,NaN
ChangeInAccruedExpense,-5.019000e+09,-2.904000e+09,-2.428000e+09,-1.558000e+09,NaN
ChangeInPayable,1.123100e+10,2.972000e+09,5.473000e+09,2.945000e+09,NaN
ChangeInAccountPayable,1.123100e+10,2.972000e+09,5.473000e+09,2.945000e+09,NaN
ChangeInInventory,-3.002000e+09,-1.884000e+09,1.449000e+09,-2.592000e+09,NaN
ChangeInReceivables,-7.333000e+09,-3.249000e+09,-8.348000e+09,-8.622000e+09,NaN
ChangesInAccountReceivables,-7.333000e+09,-3.249000e+09,-8.348000e+09,-8.622000e+09,NaN
OtherNonCashItems,-1.488000e+10,2.012000e+09,-7.480000e+08,1.696600e+10,NaN
StockBasedCompensation,1.946700e+10,2.201100e+10,2.402300e+10,1.962100e+10,NaN
DeferredTax,1.147000e+10,-4.648000e+09,-5.876000e+09,-8.148000e+09,NaN
DeferredIncomeTax,1.147000e+10,-4.648000e+09,-5.876000e+09,-8.148000e+09,NaN
DepreciationAmortizationDepletion,6.575600e+10,5.279500e+10,4.866300e+10,4.192100e+10,NaN
DepreciationAndAmortization,6.575600e+10,5.279500e+10,4.866300e+10,4.192100e+10,NaN
NetIncomeFromContinuingOperations,7.767000e+10,5.924800e+10,3.042500e+10,-2.722000e+09,NaN

In [10]:
t1.get_income_stmt()

,2025-12-31,2024-12-31,2023-12-31,2022-12-31
TaxEffectOfUnusualItems,3.004931e+09,-2.479165e+08,1.990574e+08,-3.415860e+09
TaxRateForCalcs,1.961440e-01,1.350310e-01,1.895790e-01,2.100000e-01
NormalizedEBITDA,1.500210e+11,1.256510e+11,8.835200e+10,5.461800e+10
TotalUnusualItems,1.532000e+10,-1.836000e+09,1.050000e+09,-1.626600e+10
TotalUnusualItemsExcludingGoodwill,1.532000e+10,-1.836000e+09,1.050000e+09,-1.626600e+10
NetIncomeFromContinuingOperationNetMinorityInterest,7.767000e+10,5.924800e+10,3.042500e+10,-2.722000e+09
ReconciledDepreciation,6.575600e+10,5.279500e+10,4.866300e+10,4.192100e+10
ReconciledCostOfRevenue,3.564140e+11,3.262880e+11,3.047390e+11,2.888310e+11
EBITDA,1.653410e+11,1.238150e+11,8.940200e+10,3.835200e+10
EBIT,9.958500e+10,7.102000e+10,4.073900e+10,-3.569000e+09
NetInterestIncome,2.107000e+09,2.271000e+09,-2.330000e+08,-1.378000e+09
InterestExpense,2.274000e+09,2.406000e+09,3.182000e+09,2.367000e+09
InterestIncome,4.381000e+09,4.677000e+09,2.949000e+09,9.890000e+08
NormalizedIncome,6.535493e+10,6.083608e+10,2.957406e+10,1.012814e+10
NetIncomeFromContinuingAndDiscontinuedOperation,7.767000e+10,5.924800e+10,3.042500e+10,-2.722000e+09
TotalExpenses,6.369490e+11,5.693660e+11,5.379330e+11,5.017350e+11
TotalOperatingIncomeAsReported,7.997500e+10,6.859300e+10,3.685200e+10,1.224800e+10
DilutedAverageShares,1.082700e+10,1.072100e+10,1.049200e+10,1.018900e+10
BasicAverageShares,1.065600e+10,1.047300e+10,1.030400e+10,1.018900e+10
DilutedEPS,7.170000e+00,5.530000e+00,2.900000e+00,-2.700000e-01
BasicEPS,7.290000e+00,5.660000e+00,2.950000e+00,-2.700000e-01
DilutedNIAvailtoComStockholders,7.767000e+10,5.924800e+10,3.042500e+10,-2.722000e+09
NetIncomeCommonStockholders,7.767000e+10,5.924800e+10,3.042500e+10,-2.722000e+09
NetIncome,7.767000e+10,5.924800e+10,3.042500e+10,-2.722000e+09
NetIncomeIncludingNoncontrollingInterests,7.767000e+10,5.924800e+10,3.042500e+10,-2.722000e+09
NetIncomeContinuousOperations,7.767000e+10,5.924800e+10,3.042500e+10,-2.722000e+09
EarningsFromEquityInterestNetOfTax,-5.540000e+08,-1.010000e+08,-1.200000e+07,-3.000000e+06
TaxProvision,1.908700e+10,9.265000e+09,7.120000e+09,-3.217000e+09
PretaxIncome,9.731100e+10,6.861400e+10,3.755700e+10,-5.936000e+09
OtherIncomeExpense,1.522900e+10,-2.250000e+09,9.380000e+08,-1.680600e+10
OtherNonOperatingIncomeExpenses,-9.100000e+07,-4.140000e+08,-1.120000e+08,-5.400000e+08
GainOnSaleOfSecurity,1.532000e+10,-1.836000e+09,1.050000e+09,-1.626600e+10
NetNonOperatingInterestIncomeExpense,2.107000e+09,2.271000e+09,-2.330000e+08,-1.378000e+09
InterestExpenseNonOperating,2.274000e+09,2.406000e+09,3.182000e+09,2.367000e+09
InterestIncomeNonOperating,4.381000e+09,4.677000e+09,2.949000e+09,9.890000e+08
OperatingIncome,7.997500e+10,6.859300e+10,3.685200e+10,1.224800e+10
OperatingExpense,2.805350e+11,2.430780e+11,2.331940e+11,2.129040e+11
OtherOperatingExpenses,2.222340e+11,1.878120e+11,1.770080e+11,1.587750e+11
SellingGeneralAndAdministration,5.830100e+10,5.526600e+10,5.618600e+10,5.412900e+10
SellingAndMarketingExpense,4.712900e+10,4.390700e+10,4.437000e+10,4.223800e+10
GeneralAndAdministrativeExpense,1.117200e+10,1.135900e+10,1.181600e+10,1.189100e+10
OtherGandA,1.117200e+10,1.135900e+10,1.181600e+10,1.189100e+10
GrossProfit,3.605100e+11,3.116710e+11,2.700460e+11,2.251520e+11
CostOfRevenue,3.564140e+11,3.262880e+11,3.047390e+11,2.888310e+11
TotalRevenue,7.169240e+11,6.379590e+11,5.747850e+11,5.139830e+11
OperatingRevenue,7.169240e+11,6.379590e+11,5.747850e+11,5.139830e+11

In [11]:
t1.quarterly_cash_flow

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31,2024-09-30
Free Cash Flow,1.493700e+10,4.300000e+08,3.320000e+08,-8.004000e+09,1.780200e+10,NaN
Repayment Of Debt,-5.101000e+09,-3.185000e+09,-4.632000e+09,-2.608000e+09,-6.109000e+09,NaN
Issuance Of Debt,1.711600e+10,3.223000e+09,2.093000e+09,2.561000e+09,2.554000e+09,NaN
Capital Expenditure,-3.952200e+10,-3.509500e+10,-3.218300e+10,-2.501900e+10,-2.783400e+10,NaN
Interest Paid Supplemental Data,5.630000e+08,3.770000e+08,6.470000e+08,3.620000e+08,7.710000e+08,NaN
Income Tax Paid Supplemental Data,1.521000e+09,1.136000e+09,4.761000e+09,8.770000e+08,4.146000e+09,NaN
End Cash Position,9.010600e+10,7.046400e+10,6.145300e+10,6.989300e+10,8.231200e+10,NaN
Beginning Cash Position,7.046400e+10,6.145300e+10,6.989300e+10,8.231200e+10,7.867700e+10,NaN
Effect Of Exchange Rate Changes,1.370000e+08,-3.970000e+08,1.008000e+09,4.160000e+08,-1.250000e+09,NaN
Changes In Cash,1.950500e+10,9.408000e+09,-9.448000e+09,-1.283500e+10,4.885000e+09,NaN
Financing Cash Flow,1.229100e+10,-4.400000e+07,-2.539000e+09,-4.700000e+07,-3.308000e+09,NaN
Cash Flow From Continuing Financing Activities,1.229100e+10,-4.400000e+07,-2.539000e+09,-4.700000e+07,-3.308000e+09,NaN
Net Other Financing Charges,NaN,-8.200000e+07,NaN,NaN,NaN,-78000000.0
Net Issuance Payments Of Debt,1.201500e+10,3.800000e+07,-2.539000e+09,-4.700000e+07,-3.555000e+09,NaN
Net Short Term Debt Issuance,-9.370000e+08,1.397000e+09,7.010000e+08,-2.670000e+08,-5.300000e+07,NaN
Short Term Debt Payments,-3.126000e+09,-1.826000e+09,-1.392000e+09,-2.082000e+09,-2.607000e+09,NaN
Short Term Debt Issuance,2.189000e+09,3.223000e+09,2.093000e+09,1.815000e+09,2.554000e+09,NaN
Net Long Term Debt Issuance,1.295200e+10,-1.359000e+09,-3.240000e+09,2.200000e+08,-3.502000e+09,NaN
Long Term Debt Payments,-1.975000e+09,-1.359000e+09,-3.240000e+09,-5.260000e+08,-3.502000e+09,NaN
Long Term Debt Issuance,1.492700e+10,0.000000e+00,0.000000e+00,7.460000e+08,0.000000e+00,NaN
Investing Cash Flow,-4.724500e+10,-2.607300e+10,-3.942400e+10,-2.980300e+10,-3.744300e+10,NaN
Cash Flow From Continuing Investing Activities,-4.724500e+10,-2.607300e+10,-3.942400e+10,-2.980300e+10,-3.744300e+10,NaN
Net Investment Purchase And Sale,-7.373000e+09,8.941000e+09,-6.356000e+09,-5.596000e+09,-8.856000e+09,NaN
Sale Of Investment,8.841000e+09,1.636700e+10,1.144100e+10,7.737000e+09,3.677000e+09,NaN
Purchase Of Investment,-1.621400e+10,-7.426000e+09,-1.779700e+10,-1.333300e+10,-1.253300e+10,NaN
Net Business Purchase And Sale,-1.403000e+09,-7.860000e+08,-1.700000e+09,4.800000e+07,-2.535000e+09,NaN
Sale Of Business,NaN,NaN,NaN,4.800000e+07,NaN,NaN
Purchase Of Business,-1.403000e+09,-7.860000e+08,-1.700000e+09,NaN,-2.535000e+09,-622000000.0
Net PPE Purchase And Sale,-3.846900e+10,-3.422800e+10,-3.136800e+10,-2.425500e+10,-2.605200e+10,NaN
Sale Of PPE,1.053000e+09,8.670000e+08,8.150000e+08,7.640000e+08,1.782000e+09,NaN
Purchase Of PPE,-3.952200e+10,-3.509500e+10,-3.218300e+10,-2.501900e+10,-2.783400e+10,NaN
Operating Cash Flow,5.445900e+10,3.552500e+10,3.251500e+10,1.701500e+10,4.563600e+10,NaN
Cash Flow From Continuing Operating Activities,5.445900e+10,3.552500e+10,3.251500e+10,1.701500e+10,4.563600e+10,NaN
Change In Working Capital,9.270000e+09,-7.323000e+09,-6.163000e+09,-1.575300e+10,7.100000e+09,NaN
Change In Other Working Capital,-1.910000e+08,-6.320000e+08,-1.190000e+08,7.280000e+08,1.611000e+09,NaN
Change In Other Current Assets,-5.220000e+09,-4.039000e+09,-2.971000e+09,-3.402000e+09,-4.190000e+09,NaN
Change In Payables And Accrued Expense,1.705800e+10,1.520000e+08,2.106000e+09,-1.310400e+10,1.276800e+10,NaN
Change In Accrued Expense,5.993000e+09,-1.999000e+09,-4.952000e+09,-4.061000e+09,4.042000e+09,NaN
Change In Payable,1.106500e+10,2.151000e+09,7.058000e+09,-9.043000e+09,8.726000e+09,NaN
Change In Account Payable,1.106500e+10,2.151000e+09,7.058000e+09,-9.043000e+09,8.726000e+09,NaN
Change In Inventory,3.101000e+09,-8.270000e+08,-4.054000e+09,-1.222000e+09,9.340000e+08,NaN
Change In Receivables,-5.478000e+09,-1.977000e+09,-1.125000e+09,1.247000e+09,-4.023000e+09,NaN
Changes In Account Receivables,-5.478000e+09,-1.977000e+09,-1.125000e+09,1.247000e+09,-4.023000e+09,NaN
Other Non Cash Items,-6.930000e+08,-1.011200e+10,-1.258000e+09,-2.817000e+09,-4.860000e+08,NaN
Stock Based Compensation,4.397000e+09,4.847000e+09,6.534000e+09,3.689000e+09,4.995000e+09,NaN
Deferred Tax,8.220000e+08,1.013000e+10,1.100000e+07,5.070000e+08,-1.608000e+09,NaN
Deferred Income Tax,8.220000e+08,1.013000e+10,1.100000e+07,5.070000e+08,-1.608000e+09,NaN
Depreciation Amortization Depletion,1.947100e+10,1.679600e+10,1.522700e+10,1.426200e+10,1.563100e+10,NaN
Depreciation And Amortization,1.947100e+10,1.679600e+10,1.522700e+10,1.426200e+10,1.563100e+10,NaN
Net Income From Continuing Operations,2.119200e+10,2.118700e+10,1.816400e+10,1.712700e+10,2.000400e+10,NaN