In [11]:
import numpy as np
import pandas as pd

np1=np.arange(25).reshape(5,5)
df1=pd.DataFrame(np1,index=['r1','r2','r3','r4','r5'],columns=['a','b','c','d','e'])
df1.index.name='r'
df1

     a   b   c   d   e
r
r1   0   1   2   3   4
r2   5   6   7   8   9
r3  10  11  12  13  14
r4  15  16  17  18  19
r5  20  21  22  23  24

In [12]:
np2=np.arange(100,125).reshape(5,5)
df2=pd.DataFrame(np2,index=['r1','r2','r3','r4','r6'],columns=['c1','c2','c3','c4','c5'])
df2.index.name='r'
df2

     c1   c2   c3   c4   c5
r
r1  100  101  102  103  104
r2  105  106  107  108  109
r3  110  111  112  113  114
r4  115  116  117  118  119
r6  120  121  122  123  124

In [14]:
pd.merge(df1,df2,on='r',how='outer')

       a     b     c     d     e     c1     c2     c3     c4     c5
r
r1   0.0   1.0   2.0   3.0   4.0  100.0  101.0  102.0  103.0  104.0
r2   5.0   6.0   7.0   8.0   9.0  105.0  106.0  107.0  108.0  109.0
r3  10.0  11.0  12.0  13.0  14.0  110.0  111.0  112.0  113.0  114.0
r4  15.0  16.0  17.0  18.0  19.0  115.0  116.0  117.0  118.0  119.0
r5  20.0  21.0  22.0  23.0  24.0    NaN    NaN    NaN    NaN    NaN
r6   NaN   NaN   NaN   NaN   NaN  120.0  121.0  122.0  123.0  124.0