In [ ]:
api_key='PKSFPBOGXCM4LWVR3T2JHYHAIU'
secret_key='7JFMkCuQ98bVAJHDeyo4bw3RGSic7CmpmGdUk4cntPv'

stock

In [4]:
from alpaca.data.historical.stock import StockHistoricalDataClient

# setup stock historical data client
stock_historical_data_client = StockHistoricalDataClient(api_key, secret_key)

In [5]:
from alpaca.data.requests import StockBarsRequest
from alpaca.data.timeframe import TimeFrame, TimeFrameUnit
import pendulum as dt
timez_zone="America/New_York"
current_time=dt.now(tz=timez_zone)
print(current_time)
req = StockBarsRequest(
    symbol_or_symbols = 'TSLA',
    timeframe=TimeFrame(amount = 1, unit = TimeFrameUnit.Minute), # specify timeframe
    start = current_time-dt.duration(days=10),                          # specify start datetime, default=the beginning of the current day.
    end_date=current_time#-dt.duration(days=10),                                        # specify end datetime, default=now
    # limit = 2,                                               # specify limit
)

history1=stock_historical_data_client.get_stock_bars(req).df
history1

2026-05-17 06:02:16.904050-04:00

                                      open    high       low     close  \
symbol timestamp
TSLA   2026-05-07 10:03:00+00:00  404.4500  404.45  404.0137  404.0137
       2026-05-07 10:04:00+00:00  404.0000  404.00  403.6100  403.7000
       2026-05-07 10:05:00+00:00  403.6013  403.86  403.6005  403.7600
       2026-05-07 10:06:00+00:00  403.7700  403.92  403.7200  403.8200
       2026-05-07 10:07:00+00:00  403.8100  403.87  403.5300  403.5300
...                                    ...     ...       ...       ...
       2026-05-15 23:55:00+00:00  418.3800  418.44  418.3600  418.4139
       2026-05-15 23:56:00+00:00  418.4400  418.72  418.4282  418.5900
       2026-05-15 23:57:00+00:00  418.6000  418.79  418.4500  418.5000
       2026-05-15 23:58:00+00:00  418.5300  418.53  418.1700  418.2900
       2026-05-15 23:59:00+00:00  418.2500  418.59  418.2500  418.5700

                                  volume  trade_count        vwap
symbol timestamp
TSLA   2026-05-07 10:03:00+00:00  1233.0         72.0  404.293785
       2026-05-07 10:04:00+00:00  3139.0        185.0  403.806579
       2026-05-07 10:05:00+00:00  1447.0         83.0  403.705947
       2026-05-07 10:06:00+00:00  1224.0         66.0  403.808024
       2026-05-07 10:07:00+00:00  2846.0        130.0  403.683876
...                                  ...          ...         ...
       2026-05-15 23:55:00+00:00  4561.0        124.0  418.406833
       2026-05-15 23:56:00+00:00  7891.0        214.0  418.550826
       2026-05-15 23:57:00+00:00  6172.0        205.0  418.620643
       2026-05-15 23:58:00+00:00  7183.0        171.0  418.313683
       2026-05-15 23:59:00+00:00  8213.0        180.0  418.358461

[6565 rows x 7 columns]

crypto

In [7]:
from alpaca.data.historical import CryptoHistoricalDataClient
from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame

# no keys required for crypto data
client = CryptoHistoricalDataClient()

request_params = CryptoBarsRequest(
                        symbol_or_symbols=["BTC/USD", "ETH/USD"],
                        timeframe=TimeFrame.Day,
                        start="2022-07-01"
                 )

bars = client.get_crypto_bars(request_params).df
bars

                                        open       high          low  \
symbol  timestamp
BTC/USD 2022-07-01 00:00:00+00:00  19935.530  20896.360  18940.00000
        2022-07-02 00:00:00+00:00  19261.580  19441.900  18956.79000
        2022-07-03 00:00:00+00:00  19227.690  19625.320  18752.98000
        2022-07-04 00:00:00+00:00  19292.880  20320.000  19034.13000
        2022-07-05 00:00:00+00:00  20212.610  20728.500  19281.37000
...                                      ...        ...          ...
ETH/USD 2026-05-13 00:00:00+00:00   2275.190   2322.570   2233.40000
        2026-05-14 00:00:00+00:00   2259.042   2318.965   2237.66500
        2026-05-15 00:00:00+00:00   2283.523   2299.315   2203.43000
        2026-05-16 00:00:00+00:00   2222.635   2230.900   2162.47538
        2026-05-17 00:00:00+00:00   2180.610   2191.885   2167.68700

                                        close       volume  trade_count  \
symbol  timestamp
BTC/USD 2022-07-01 00:00:00+00:00  19256.7500  9747.183616     148392.0
        2022-07-02 00:00:00+00:00  19226.5300  3913.931431      66000.0
        2022-07-03 00:00:00+00:00  19290.6800  3275.136164      94793.0
        2022-07-04 00:00:00+00:00  20212.6100  6404.379456     213657.0
        2022-07-05 00:00:00+00:00  20157.2200  9137.287715     270041.0
...                                       ...          ...          ...
ETH/USD 2026-05-13 00:00:00+00:00   2257.6300    41.917820        268.0
        2026-05-14 00:00:00+00:00   2282.4995    21.580931        309.0
        2026-05-15 00:00:00+00:00   2223.5200    54.425800        355.0
        2026-05-16 00:00:00+00:00   2179.4500    40.495620        354.0
        2026-05-17 00:00:00+00:00   2189.9195     1.641290        113.0

                                           vwap
symbol  timestamp
BTC/USD 2022-07-01 00:00:00+00:00  19619.593190
        2022-07-02 00:00:00+00:00  19214.413569
        2022-07-03 00:00:00+00:00  19160.073904
        2022-07-04 00:00:00+00:00  19653.972156
        2022-07-05 00:00:00+00:00  19980.483912
...                                         ...
ETH/USD 2026-05-13 00:00:00+00:00   2252.839288
        2026-05-14 00:00:00+00:00   2269.190257
        2026-05-15 00:00:00+00:00   2228.630988
        2026-05-16 00:00:00+00:00   2176.504049
        2026-05-17 00:00:00+00:00   2179.525218

[2834 rows x 7 columns]