In [ ]:
api_key='PKSFPBOGXCM4LWVR3T2JHYHAIU'
secret_key='7JFMkCuQ98bVAJHDeyo4bw3RGSic7CmpmGdUk4cntPv'

stock

In [4]:
from alpaca.data.historical.stock import StockHistoricalDataClient

# setup stock historical data client
stock_historical_data_client = StockHistoricalDataClient(api_key, secret_key)

In [5]:
from alpaca.data.requests import StockBarsRequest
from alpaca.data.timeframe import TimeFrame, TimeFrameUnit
import pendulum as dt
timez_zone="America/New_York"
current_time=dt.now(tz=timez_zone)
print(current_time)
req = StockBarsRequest(
    symbol_or_symbols = 'TSLA',
    timeframe=TimeFrame(amount = 1, unit = TimeFrameUnit.Minute), # specify timeframe
    start = current_time-dt.duration(days=10),                          # specify start datetime, default=the beginning of the current day.
    end_date=current_time#-dt.duration(days=10),                                        # specify end datetime, default=now
    # limit = 2,                                               # specify limit
)

history1=stock_historical_data_client.get_stock_bars(req).df
history1

2026-05-17 06:02:16.904050-04:00

                                      open    high       low     close  \
symbol timestamp
TSLA   2026-05-07 10:03:00+00:00  404.4500  404.45  404.0137  404.0137
       2026-05-07 10:04:00+00:00  404.0000  404.00  403.6100  403.7000
       2026-05-07 10:05:00+00:00  403.6013  403.86  403.6005  403.7600
       2026-05-07 10:06:00+00:00  403.7700  403.92  403.7200  403.8200
       2026-05-07 10:07:00+00:00  403.8100  403.87  403.5300  403.5300
...                                    ...     ...       ...       ...
       2026-05-15 23:55:00+00:00  418.3800  418.44  418.3600  418.4139
       2026-05-15 23:56:00+00:00  418.4400  418.72  418.4282  418.5900
       2026-05-15 23:57:00+00:00  418.6000  418.79  418.4500  418.5000
       2026-05-15 23:58:00+00:00  418.5300  418.53  418.1700  418.2900
       2026-05-15 23:59:00+00:00  418.2500  418.59  418.2500  418.5700

                                  volume  trade_count        vwap
symbol timestamp
TSLA   2026-05-07 10:03:00+00:00  1233.0         72.0  404.293785
       2026-05-07 10:04:00+00:00  3139.0        185.0  403.806579
       2026-05-07 10:05:00+00:00  1447.0         83.0  403.705947
       2026-05-07 10:06:00+00:00  1224.0         66.0  403.808024
       2026-05-07 10:07:00+00:00  2846.0        130.0  403.683876
...                                  ...          ...         ...
       2026-05-15 23:55:00+00:00  4561.0        124.0  418.406833
       2026-05-15 23:56:00+00:00  7891.0        214.0  418.550826
       2026-05-15 23:57:00+00:00  6172.0        205.0  418.620643
       2026-05-15 23:58:00+00:00  7183.0        171.0  418.313683
       2026-05-15 23:59:00+00:00  8213.0        180.0  418.358461

[6565 rows x 7 columns]

crypto

In [7]:
from alpaca.data.historical import CryptoHistoricalDataClient
from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame

# no keys required for crypto data
client = CryptoHistoricalDataClient()

request_params = CryptoBarsRequest(
                        symbol_or_symbols=["BTC/USD", "ETH/USD"],
                        timeframe=TimeFrame.Day,
                        start="2022-07-01"
                 )

bars = client.get_crypto_bars(request_params).df
bars

                                        open       high          low  \
symbol  timestamp
BTC/USD 2022-07-01 00:00:00+00:00  19935.530  20896.360  18940.00000
        2022-07-02 00:00:00+00:00  19261.580  19441.900  18956.79000
        2022-07-03 00:00:00+00:00  19227.690  19625.320  18752.98000
        2022-07-04 00:00:00+00:00  19292.880  20320.000  19034.13000
        2022-07-05 00:00:00+00:00  20212.610  20728.500  19281.37000
...                                      ...        ...          ...
ETH/USD 2026-05-13 00:00:00+00:00   2275.190   2322.570   2233.40000
        2026-05-14 00:00:00+00:00   2259.042   2318.965   2237.66500
        2026-05-15 00:00:00+00:00   2283.523   2299.315   2203.43000
        2026-05-16 00:00:00+00:00   2222.635   2230.900   2162.47538
        2026-05-17 00:00:00+00:00   2180.610   2191.885   2167.68700

                                        close       volume  trade_count  \
symbol  timestamp
BTC/USD 2022-07-01 00:00:00+00:00  19256.7500  9747.183616     148392.0
        2022-07-02 00:00:00+00:00  19226.5300  3913.931431      66000.0
        2022-07-03 00:00:00+00:00  19290.6800  3275.136164      94793.0
        2022-07-04 00:00:00+00:00  20212.6100  6404.379456     213657.0
        2022-07-05 00:00:00+00:00  20157.2200  9137.287715     270041.0
...                                       ...          ...          ...
ETH/USD 2026-05-13 00:00:00+00:00   2257.6300    41.917820        268.0
        2026-05-14 00:00:00+00:00   2282.4995    21.580931        309.0
        2026-05-15 00:00:00+00:00   2223.5200    54.425800        355.0
        2026-05-16 00:00:00+00:00   2179.4500    40.495620        354.0
        2026-05-17 00:00:00+00:00   2189.9195     1.641290        113.0

                                           vwap
symbol  timestamp
BTC/USD 2022-07-01 00:00:00+00:00  19619.593190
        2022-07-02 00:00:00+00:00  19214.413569
        2022-07-03 00:00:00+00:00  19160.073904
        2022-07-04 00:00:00+00:00  19653.972156
        2022-07-05 00:00:00+00:00  19980.483912
...                                         ...
ETH/USD 2026-05-13 00:00:00+00:00   2252.839288
        2026-05-14 00:00:00+00:00   2269.190257
        2026-05-15 00:00:00+00:00   2228.630988
        2026-05-16 00:00:00+00:00   2176.504049
        2026-05-17 00:00:00+00:00   2179.525218

[2834 rows x 7 columns]

option

In [8]:
from alpaca.trading.requests import GetOptionContractsRequest
from alpaca.trading.enums import AssetStatus
from alpaca.trading.client import TradingClient
# setup clients
trade_client = TradingClient(api_key=api_key, secret_key=secret_key)

# get list of options contracts for the given underlying symbol (e.g. SPY,AAPL)
# - get_option_contracts() is a new method to get list of options contracts
# - in this example, we get 2 options contracts for SPY,AAPL
# - you can continue to fetch options contracts by specifying page_token from next_page_token of response
underlying_symbols = ["SPY"]
req = GetOptionContractsRequest(
    underlying_symbols = underlying_symbols,               # specify underlying symbols
    status = AssetStatus.ACTIVE,                           # specify asset status: active (default)
    expiration_date = None,                                # specify expiration date (specified date + 1 day range)
    expiration_date_gte = None,                            # we can pass date object
    expiration_date_lte = None,                            # or string (YYYY-MM-DD)
    root_symbol = None,                                    # specify root symbol
    type = None,                                           # specify option type (ContractType.CALL or ContractType.PUT)
    style = None,                                          # specify option style (ContractStyle.AMERICAN or ContractStyle.EUROPEAN)
    strike_price_gte = None,                               # specify strike price range
    strike_price_lte = None,                               # specify strike price range
    # limit = 2,                                             # specify limit
    page_token = None,                                     # specify page token
)
res = trade_client.get_option_contracts(req)
res

{   'next_page_token': 'MTAw',
    'option_contracts': [   {   'close_price': None,
                                'close_price_date': None,
                                'expiration_date': datetime.date(2026, 5, 18),
                                'id': 'b14b84da-b0b1-4e51-8de7-e12277b3e0d8',
                                'name': 'SPY May 18 2026 500 Call',
                                'open_interest': None,
                                'open_interest_date': None,
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 500.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY260518C00500000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'},
                            {   'close_price': None,
                                'close_price_date': None,
                                'expiration_date': datetime.date(2026, 5, 18),
                                'id': '7c12bd10-43d4-4f31-b470-9a3c17b992d8',
                                'name': 'SPY May 18 2026 505 Call',
                                'open_interest': None,
                                'open_interest_date': None,
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 505.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY260518C00505000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'},
                            {   'close_price': None,
                                'close_price_date': None,
                                'expiration_date': datetime.date(2026, 5, 18),
                                'id': '91c107c6-d98c-4314-808d-4dd6e7f3c3ec',
                                'name': 'SPY May 18 2026 510 Call',
                                'open_interest': None,
                                'open_interest_date': None,
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 510.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY260518C00510000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'},
                            {   'close_price': None,
                                'close_price_date': None,
                                'expiration_date': datetime.date(2026, 5, 18),
                                'id': '4c0737f4-9cba-465f-a4bb-20c36c9451c4',
                                'name': 'SPY May 18 2026 515 Call',
                                'open_interest': None,
                                'open_interest_date': None,
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 515.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY260518C00515000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'},
                            {   'close_price': None,
                                'close_price_date': None,
                                'expiration_date': datetime.date(2026, 5, 18),
                                'id': '17e33ce0-9799-4558-9066-8b1bfd79bb8f',
                                'name': 'SPY May 18 2026 520 Call',
                                'open_interest': None,
                                'open_interest_date': None,
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 520.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY260518C00520000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'},
                            {   'close_price': None,
                                'close_price_date': None,
                                'expiration_date': datetime.date(2026, 5, 18),
                                'id': '789c9416-69be-4e5a-964e-4bed87165835',
                                'name': 'SPY May 18 2026 525 Call',
                                'open_interest': None,
                                'open_interest_date': None,
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 525.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY260518C00525000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'},
                            {   'close_price': '212.28',
                                'close_price_date': datetime.date(2026, 5, 15),
                                'expiration_date': datetime.date(2026, 5, 18),
                                'id': 'acaeb2ea-ff82-4cee-bc6a-47d4bcdb8cbf',
                                'name': 'SPY May 18 2026 530 Call',
                                'open_interest': None,
                                'open_interest_date': None,
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 530.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY260518C00530000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'},
                            {   'close_price': None,
                                'close_price_date': None,
                                'expiration_date': datetime.date(2026, 5, 18),
                                'id': '4295beff-287b-40b2-baa7-5c4909f3c317',
                                'name': 'SPY May 18 2026 535 Call',
                                'open_interest': None,
                                'open_interest_date': None,
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 535.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY260518C00535000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'},
                            {   'close_price': None,
                                'close_price_date': None,
                                'expiration_date': datetime.date(2026, 5, 18),
                                'id': '4fdcf845-211b-4232-b6f4-182303170322',
                                'name': 'SPY May 18 2026 540 Call',
                                'open_interest': None,
                                'open_interest_date': None,
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 540.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY260518C00540000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'},
                            {   'close_price': None,
                                'close_price_date': None,
                                'expiration_date': datetime.date(2026, 5, 18),
                                'id': 'a9f4846e-26f0-4fbf-807b-4ac56839014b',
                                'name': 'SPY May 18 2026 545 Call',
                                'open_interest': None,
                                'open_interest_date': None,
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 545.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY260518C00545000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'},
                            {   'close_price': None,
                                'close_price_date': None,
                                'expiration_date': datetime.date(2026, 5, 18),
                                'id': '5e5c08f4-4f76-4a2e-a973-5a9dbb9c39e0',
                                'name': 'SPY May 18 2026 550 Call',
                                'open_interest': None,
                                'open_interest_date': None,
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 550.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY260518C00550000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'},
                            {   'close_price': None,
                                'close_price_date': None,
                                'expiration_date': datetime.date(2026, 5, 18),
                                'id': '8ba443b8-273c-466d-aa5a-8a8aba395328',
                                'name': 'SPY May 18 2026 555 Call',
                                'open_interest': None,
                                'open_interest_date': None,
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 555.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY260518C00555000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'},
                            {   'close_price': None,
                                'close_price_date': None,
                                'expiration_date': datetime.date(2026, 5, 18),
                                'id': 'c74994b3-2ec8-4872-8faa-401b5b3fc3f5',
                                'name': 'SPY May 18 2026 560 Call',
                                'open_interest': None,
                                'open_interest_date': None,
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 560.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY260518C00560000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'},
                            {   'close_price': None,
                                'close_price_date': None,
                                'expiration_date': datetime.date(2026, 5, 18),
                                'id': '189c68e0-80ca-48fb-9652-0b16279eabf3',
                                'name': 'SPY May 18 2026 565 Call',
                                'open_interest': None,
                                'open_interest_date': None,
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 565.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY260518C00565000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'},
                            {   'close_price': None,
                                'close_price_date': None,
                                'expiration_date': datetime.date(2026, 5, 18),
                                'id': '6a1a3ce7-a5d8-4f5e-885e-28cbc37fd2e6',
                                'name': 'SPY May 18 2026 570 Call',
                                'open_interest': None,
                                'open_interest_date': None,
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 570.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY260518C00570000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'},
                            {   'close_price': None,
                                'close_price_date': None,
                                'expiration_date': datetime.date(2026, 5, 18),
                                'id': '2303f0e6-9330-44e6-952d-ce4b99b34e13',
                                'name': 'SPY May 18 2026 575 Call',
                                'open_interest': None,
                                'open_interest_date': None,
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 575.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY260518C00575000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'},
                            {   'close_price': None,
                                'close_price_date': None,
                                'expiration_date': datetime.date(2026, 5, 18),
                                'id': '237a4bf9-964c-46b3-9b6b-06a2a708546c',
                                'name': 'SPY May 18 2026 580 Call',
                                'open_interest': None,
                                'open_interest_date': None,
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 580.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY260518C00580000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'},
                            {   'close_price': None,
                                'close_price_date': None,
                                'expiration_date': datetime.date(2026, 5, 18),
                                'id': '3914560d-1221-42ff-b5a7-ef91d8baa06b',
                                'name': 'SPY May 18 2026 585 Call',
                                'open_interest': None,
                                'open_interest_date': None,
                                'root_symbol': 'SPY',
                                'size': '100',
                                'status': <AssetStatus.ACTIVE: 'active'>,
                                'strike_price': 585.0,
                                'style': <ExerciseStyle.AMERICAN: 'american'>,
                                'symbol': 'SPY260518C00585000',
                                'tradable': True,
                                'type': <ContractType.CALL: 'call'>,
                                'underlying_asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
                                'underlying_symbol': 'SPY'},
                            {   'close_price': None,

In [10]:
from alpaca.data.historical.option import OptionHistoricalDataClient
from alpaca.data.requests import OptionBarsRequest
from alpaca.data.timeframe import TimeFrame, TimeFrameUnit

current_time=dt.now(timez_zone)

option_historical_data_client=OptionHistoricalDataClient(api_key=api_key,secret_key=secret_key)
# get options historical bars by symbol
req = OptionBarsRequest(
    symbol_or_symbols = 'SPY260518C00740000',
    timeframe = TimeFrame(amount = 1, unit = TimeFrameUnit.Hour),   # specify timeframe
    start = current_time-dt.duration(days=7),                          # specify start datetime, default=the beginning of the current day.
    end_date=current_time#-dt.duration(days=10),                                             # specify end datetime, default=now
    # limit = 2,                                                      # specify limit
)
history3=option_historical_data_client.get_option_bars(req).df
history3

                                               open   high   low  close  \
symbol             timestamp
SPY260518C00740000 2026-05-11 13:00:00+00:00   4.12   5.35  4.12   5.12
                   2026-05-11 14:00:00+00:00   5.09   5.60  4.67   5.46
                   2026-05-11 15:00:00+00:00   5.37   5.74  5.14   5.67
                   2026-05-11 16:00:00+00:00   5.65   5.85  5.09   5.30
                   2026-05-11 17:00:00+00:00   5.35   6.00  5.04   5.81
                   2026-05-11 18:00:00+00:00   5.83   5.96  4.89   4.89
                   2026-05-11 19:00:00+00:00   4.83   5.14  4.74   5.06
                   2026-05-11 20:00:00+00:00   5.20   5.24  4.70   5.07
                   2026-05-12 13:00:00+00:00   3.90   3.90  3.03   3.07
                   2026-05-12 14:00:00+00:00   3.00   3.32  2.40   2.44
                   2026-05-12 15:00:00+00:00   2.46   2.46  1.93   2.00
                   2026-05-12 16:00:00+00:00   2.17   2.21  1.78   1.79
                   2026-05-12 17:00:00+00:00   1.86   2.68  1.81   2.68
                   2026-05-12 18:00:00+00:00   2.69   3.25  2.58   3.01
                   2026-05-12 19:00:00+00:00   3.07   4.22  3.07   3.84
                   2026-05-12 20:00:00+00:00   3.79   3.79  3.44   3.44
                   2026-05-13 13:00:00+00:00   3.75   3.75  2.80   3.25
                   2026-05-13 14:00:00+00:00   3.25   3.97  3.20   3.85
                   2026-05-13 15:00:00+00:00   3.94   4.65  3.85   4.38
                   2026-05-13 16:00:00+00:00   4.39   5.91  4.39   5.70
                   2026-05-13 17:00:00+00:00   6.00   6.33  5.74   5.74
                   2026-05-13 18:00:00+00:00   5.75   6.80  5.75   6.01
                   2026-05-13 19:00:00+00:00   6.50   6.63  5.74   5.82
                   2026-05-13 20:00:00+00:00   5.70   6.01  5.70   5.97
                   2026-05-14 13:00:00+00:00   6.27   8.06  6.27   7.55
                   2026-05-14 14:00:00+00:00   7.00   9.11  6.95   9.11
                   2026-05-14 15:00:00+00:00   9.17  10.60  9.17  10.56
                   2026-05-14 16:00:00+00:00  10.60  10.67  8.99   9.00
                   2026-05-14 17:00:00+00:00   9.49   9.54  8.28   9.45
                   2026-05-14 18:00:00+00:00   8.73   9.60  8.73   9.09
                   2026-05-14 19:00:00+00:00   9.83   9.83  9.12   9.12
                   2026-05-14 20:00:00+00:00   9.42   9.58  9.42   9.54
                   2026-05-15 13:00:00+00:00   3.51   4.60  2.71   3.15
                   2026-05-15 14:00:00+00:00   3.24   4.97  3.06   3.81
                   2026-05-15 15:00:00+00:00   3.81   4.16  2.76   3.24
                   2026-05-15 16:00:00+00:00   3.27   3.80  2.94   3.41
                   2026-05-15 17:00:00+00:00   3.32   4.55  3.24   4.55
                   2026-05-15 18:00:00+00:00   4.60   4.90  3.21   3.65
                   2026-05-15 19:00:00+00:00   3.66   3.70  2.13   2.39
                   2026-05-15 20:00:00+00:00   2.29   2.29  1.50   1.83

                                               volume  trade_count      vwap
symbol             timestamp
SPY260518C00740000 2026-05-11 13:00:00+00:00    341.0         69.0  4.985367
                   2026-05-11 14:00:00+00:00    617.0        107.0  5.262058
                   2026-05-11 15:00:00+00:00   1455.0        114.0  5.573725
                   2026-05-11 16:00:00+00:00    296.0         56.0  5.475237
                   2026-05-11 17:00:00+00:00    627.0        105.0  5.451770
                   2026-05-11 18:00:00+00:00    315.0         53.0  5.707524
                   2026-05-11 19:00:00+00:00    393.0         96.0  4.873028
                   2026-05-11 20:00:00+00:00     65.0         26.0  5.044769
                   2026-05-12 13:00:00+00:00    278.0         75.0  3.455611
                   2026-05-12 14:00:00+00:00    317.0         98.0  2.692461
                   2026-05-12 15:00:00+00:00    316.0         78.0  2.167184
                   2026-05-12 16:00:00+00:00    214.0         62.0  1.934393
                   2026-05-12 17:00:00+00:00    359.0         79.0  2.438440
                   2026-05-12 18:00:00+00:00    480.0        113.0  2.982583
                   2026-05-12 19:00:00+00:00    802.0        163.0  3.720723
                   2026-05-12 20:00:00+00:00    106.0         15.0  3.542359
                   2026-05-13 13:00:00+00:00    363.0        112.0  3.244931
                   2026-05-13 14:00:00+00:00    759.0        181.0  3.646192
                   2026-05-13 15:00:00+00:00   1644.0        214.0  4.203534
                   2026-05-13 16:00:00+00:00    692.0        148.0  5.189003
                   2026-05-13 17:00:00+00:00   1139.0         76.0  5.989052
                   2026-05-13 18:00:00+00:00    125.0         36.0  6.423280
                   2026-05-13 19:00:00+00:00     86.0         33.0  6.276860
                   2026-05-13 20:00:00+00:00    179.0         18.0  5.821900
                   2026-05-14 13:00:00+00:00    333.0         98.0  7.475555
                   2026-05-14 14:00:00+00:00    539.0        153.0  7.836976
                   2026-05-14 15:00:00+00:00    324.0         66.0  9.761667
                   2026-05-14 16:00:00+00:00    602.0         51.0  9.780847
                   2026-05-14 17:00:00+00:00    226.0         37.0  8.914115
                   2026-05-14 18:00:00+00:00     38.0         16.0  9.119474
                   2026-05-14 19:00:00+00:00     25.0         12.0  9.431200
                   2026-05-14 20:00:00+00:00     10.0          4.0  9.526000
                   2026-05-15 13:00:00+00:00  10841.0       1876.0  3.489863
                   2026-05-15 14:00:00+00:00   9986.0       1827.0  3.993061
                   2026-05-15 15:00:00+00:00   3396.0        785.0  3.364614
                   2026-05-15 16:00:00+00:00   4611.0        661.0  3.334674
                   2026-05-15 17:00:00+00:00   2462.0        472.0  3.952535
                   2026-05-15 18:00:00+00:00   2430.0        434.0  3.807432
                   2026-05-15 19:00:00+00:00  11725.0       1864.0  2.755449
                   2026-05-15 20:00:00+00:00   7334.0        777.0  1.749588

In [12]:
from alpaca.data.historical import CryptoHistoricalDataClient
from alpaca.data.requests import CryptoLatestQuoteRequest

# no keys required
client = CryptoHistoricalDataClient()

# single symbol request
request_params = CryptoLatestQuoteRequest(symbol_or_symbols="ETH/USD")

latest_quote = client.get_crypto_latest_quote(request_params)
print(latest_quote)
# must use symbol to access even though it is single symbol
latest_quote["ETH/USD"].ask_price

{'ETH/USD': {   'ask_exchange': None,
    'ask_price': 2195.7,
    'ask_size': 10.11,
    'bid_exchange': None,
    'bid_price': 2193.65,
    'bid_size': 9.9874,
    'conditions': None,
    'symbol': 'ETH/USD',
    'tape': None,
    'timestamp': datetime.datetime(2026, 5, 17, 10, 17, 31, 431479, tzinfo=TzInfo(0))}}

2195.7