In [1]:
!pip3 install yfinance

Collecting yfinance
  Downloading yfinance-1.2.0-py2.py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: pandas>=1.3.0 in ./.venv/lib/python3.13/site-packages (from yfinance) (3.0.1)
Requirement already satisfied: numpy>=1.16.5 in ./.venv/lib/python3.13/site-packages (from yfinance) (2.4.3)
Requirement already satisfied: requests>=2.31 in ./.venv/lib/python3.13/site-packages (from yfinance) (2.32.5)
Collecting multitasking>=0.0.7 (from yfinance)
  Using cached multitasking-0.0.12-py3-none-any.whl
Requirement already satisfied: platformdirs>=2.0.0 in ./.venv/lib/python3.13/site-packages (from yfinance) (4.9.4)
Collecting pytz>=2022.5 (from yfinance)
  Downloading pytz-2026.1.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting frozendict>=2.3.4 (from yfinance)
  Using cached frozendict-2.4.7-py3-none-any.whl.metadata (23 kB)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-4.0.3-py3-none-any.whl.metadata (8.6 kB)
Collecting beautifulsoup4>=4.11.1 (from yfinance)
  Using cached beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting curl_cffi<0.14,>=0.7 (from yfinance)
  Using cached curl_cffi-0.13.0-cp39-abi3-macosx_11_0_arm64.whl.metadata (13 kB)
Collecting protobuf>=3.19.0 (from yfinance)
  Downloading protobuf-7.34.1-cp310-abi3-macosx_10_9_universal2.whl.metadata (595 bytes)
Collecting websockets>=13.0 (from yfinance)
  Using cached websockets-16.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (6.8 kB)
Collecting cffi>=1.12.0 (from curl_cffi<0.14,>=0.7->yfinance)
  Using cached cffi-2.0.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.6 kB)
Requirement already satisfied: certifi>=2024.2.2 in ./.venv/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2026.2.25)
Collecting soupsieve>=1.6.1 (from beautifulsoup4>=4.11.1->yfinance)
  Using cached soupsieve-2.8.3-py3-none-any.whl.metadata (4.6 kB)
Collecting typing-extensions>=4.0.0 (from beautifulsoup4>=4.11.1->yfinance)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pycparser (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance)
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.6.3)
Downloading yfinance-1.2.0-py2.py3-none-any.whl (130 kB)
Using cached curl_cffi-0.13.0-cp39-abi3-macosx_11_0_arm64.whl (3.0 MB)
Using cached beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Using cached cffi-2.0.0-cp313-cp313-macosx_11_0_arm64.whl (181 kB)
Using cached frozendict-2.4.7-py3-none-any.whl (16 kB)
Downloading peewee-4.0.3-py3-none-any.whl (144 kB)
Downloading protobuf-7.34.1-cp310-abi3-macosx_10_9_universal2.whl (429 kB)
Downloading pytz-2026.1.post1-py2.py3-none-any.whl (510 kB)
Using cached soupsieve-2.8.3-py3-none-any.whl (37 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached websockets-16.0-cp313-cp313-macosx_11_0_arm64.whl (175 kB)
Using cached pycparser-3.0-py3-none-any.whl (48 kB)
Installing collected packages: pytz, peewee, multitasking, websockets, typing-extensions, soupsieve, pycparser, protobuf, frozendict, cffi, beautifulsoup4, curl_cffi, yfinance
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/13 [yfinance]/13 [cffi]ckets]
Successfully installed beautifulsoup4-4.14.3 cffi-2.0.0 curl_cffi-0.13.0 frozendict-2.4.7 multitasking-0.0.12 peewee-4.0.3 protobuf-7.34.1 pycparser-3.0 pytz-2026.1.post1 soupsieve-2.8.3 typing-extensions-4.15.0 websockets-16.0 yfinance-1.2.0

In [5]:
import yfinance as yf
df=yf.download('AAPL',period='1y',interval='1h',multi_level_index=False)
df

[*********************100%***********************]  1 of 1 completed

,Close,High,Low,Open,Volume
Datetime,,,,,
2025-03-28 13:30:00+00:00,219.910004,223.800003,219.695007,221.649002,8900229
2025-03-28 14:30:00+00:00,219.979996,220.649994,219.169998,219.889999,4819013
2025-03-28 15:30:00+00:00,218.690002,220.220001,218.350006,219.891098,3075097
2025-03-28 16:30:00+00:00,218.490005,219.119995,218.210007,218.669998,3059478
2025-03-28 17:30:00+00:00,219.050003,219.166504,218.179993,218.500000,2307054
...,...,...,...,...,...
2026-03-27 15:30:00+00:00,251.779999,253.240005,251.690002,252.619995,3302520
2026-03-27 16:30:00+00:00,250.410004,252.759995,250.369995,251.774994,3282303
2026-03-27 17:30:00+00:00,249.384995,250.580002,248.634995,250.410004,4579763
2026-03-27 18:30:00+00:00,248.409897,249.520004,248.250000,249.419998,4113587
2026-03-27 19:30:00+00:00,248.619995,249.369995,248.070007,248.410004,5252096

In [6]:
df=df.reset_index()
df

,Datetime,Close,High,Low,Open,Volume
0,2025-03-28 13:30:00+00:00,219.910004,223.800003,219.695007,221.649002,8900229
1,2025-03-28 14:30:00+00:00,219.979996,220.649994,219.169998,219.889999,4819013
2,2025-03-28 15:30:00+00:00,218.690002,220.220001,218.350006,219.891098,3075097
3,2025-03-28 16:30:00+00:00,218.490005,219.119995,218.210007,218.669998,3059478
4,2025-03-28 17:30:00+00:00,219.050003,219.166504,218.179993,218.500000,2307054
...,...,...,...,...,...,...
1731,2026-03-27 15:30:00+00:00,251.779999,253.240005,251.690002,252.619995,3302520
1732,2026-03-27 16:30:00+00:00,250.410004,252.759995,250.369995,251.774994,3282303
1733,2026-03-27 17:30:00+00:00,249.384995,250.580002,248.634995,250.410004,4579763
1734,2026-03-27 18:30:00+00:00,248.409897,249.520004,248.250000,249.419998,4113587
1735,2026-03-27 19:30:00+00:00,248.619995,249.369995,248.070007,248.410004,5252096

In [7]:
df['Datetime'].dt.tz_localize(None)

0      2025-03-28 13:30:00
1      2025-03-28 14:30:00
2      2025-03-28 15:30:00
3      2025-03-28 16:30:00
4      2025-03-28 17:30:00
               ...
1731   2026-03-27 15:30:00
1732   2026-03-27 16:30:00
1733   2026-03-27 17:30:00
1734   2026-03-27 18:30:00
1735   2026-03-27 19:30:00
Name: Datetime, Length: 1736, dtype: datetime64[s]

In [8]:

df['Datetime'].dt.tz_convert("America/New_York")

0      2025-03-28 09:30:00-04:00
1      2025-03-28 10:30:00-04:00
2      2025-03-28 11:30:00-04:00
3      2025-03-28 12:30:00-04:00
4      2025-03-28 13:30:00-04:00
                  ...
1731   2026-03-27 11:30:00-04:00
1732   2026-03-27 12:30:00-04:00
1733   2026-03-27 13:30:00-04:00
1734   2026-03-27 14:30:00-04:00
1735   2026-03-27 15:30:00-04:00
Name: Datetime, Length: 1736, dtype: datetime64[s, America/New_York]

In [2]:
import pandas as pd
data=pd.read_csv('/Users/algo trading 2026/batch36/13_datetime_tz/candle.csv')
data

,Datetime,Close,High,Low,Open,Volume
0,2026-01-26 14:30:00+00:00,442.665009,445.029999,442.130005,445.029999,1121872
1,2026-01-26 14:31:00+00:00,443.399994,443.529999,442.269989,442.665009,268066
2,2026-01-26 14:32:00+00:00,442.079895,443.399994,441.470001,443.364990,292367
3,2026-01-26 14:33:00+00:00,441.380005,442.750000,441.380005,442.029999,213710
4,2026-01-26 14:34:00+00:00,439.649994,441.378387,439.600006,441.378387,389645
...,...,...,...,...,...,...
1930,2026-01-30 20:55:00+00:00,432.059998,432.609985,430.250000,432.609985,496455
1931,2026-01-30 20:56:00+00:00,430.798615,432.100006,430.519989,432.079987,396241
1932,2026-01-30 20:57:00+00:00,430.739990,430.869995,430.399994,430.859985,313633
1933,2026-01-30 20:58:00+00:00,430.600006,430.850006,430.399994,430.750000,353859
1934,2026-01-30 20:59:00+00:00,430.436005,430.920013,430.100006,430.609985,922192

In [3]:
data['Datetime']=pd.to_datetime(data['Datetime'],unit='s')
data

,Datetime,Close,High,Low,Open,Volume
0,2026-01-26 14:30:00+00:00,442.665009,445.029999,442.130005,445.029999,1121872
1,2026-01-26 14:31:00+00:00,443.399994,443.529999,442.269989,442.665009,268066
2,2026-01-26 14:32:00+00:00,442.079895,443.399994,441.470001,443.364990,292367
3,2026-01-26 14:33:00+00:00,441.380005,442.750000,441.380005,442.029999,213710
4,2026-01-26 14:34:00+00:00,439.649994,441.378387,439.600006,441.378387,389645
...,...,...,...,...,...,...
1930,2026-01-30 20:55:00+00:00,432.059998,432.609985,430.250000,432.609985,496455
1931,2026-01-30 20:56:00+00:00,430.798615,432.100006,430.519989,432.079987,396241
1932,2026-01-30 20:57:00+00:00,430.739990,430.869995,430.399994,430.859985,313633
1933,2026-01-30 20:58:00+00:00,430.600006,430.850006,430.399994,430.750000,353859
1934,2026-01-30 20:59:00+00:00,430.436005,430.920013,430.100006,430.609985,922192

In [7]:
data['Datetime'].dt.tz_convert("Asia/Kolkata").dt.tz_localize(None)

0      2026-01-26 20:00:00
1      2026-01-26 20:01:00
2      2026-01-26 20:02:00
3      2026-01-26 20:03:00
4      2026-01-26 20:04:00
               ...
1930   2026-01-31 02:25:00
1931   2026-01-31 02:26:00
1932   2026-01-31 02:27:00
1933   2026-01-31 02:28:00
1934   2026-01-31 02:29:00
Name: Datetime, Length: 1935, dtype: datetime64[us]