In [2]:
import pandas as pd
df=pd.read_csv('/Users/algo trading 2026/batch36/11_pandas/sp500_companies.csv')
df

,Company name,Symbol,Sector[15],Date added[16]
0,Adani Enterprises,ADANIENT,Metals & Mining,30 September 2022
1,Adani Ports & SEZ,ADANIPORTS,Services,28 September 2015
2,Apollo Hospitals,APOLLOHOSP,Healthcare,31 March 2022
3,Asian Paints,ASIANPAINT,Consumer Durables,27 April 2012[a]
4,Axis Bank,AXISBANK,Financial Services,27 March 2009
5,Bajaj Auto,BAJAJ-AUTO,Automobile and Auto Components,1 October 2010[b]
6,Bajaj Finance,BAJFINANCE,Financial Services,29 September 2017
7,Bajaj Finserv,BAJAJFINSV,Financial Services,2 April 2018
8,Bharat Electronics,BEL,Capital Goods,30 September 2024
9,Bharti Airtel,BHARTIARTL,Telecommunication,1 March 2004
10,Cipla,CIPLA,Healthcare,7 October 1998
11,Coal India,COALINDIA,"Oil, Gas & Consumable Fuels",10 October 2011
12,Dr. Reddy's Laboratories,DRREDDY,Healthcare,1 October 2010[c]
13,Eicher Motors,EICHERMOT,Automobile and Auto Components,1 April 2016
14,Eternal,ETERNAL,Consumer Services,28 March 2025
15,Grasim Industries,GRASIM,Construction Materials,2 April 2018[d]
16,HCLTech,HCLTECH,Information Technology,28 October 2002
17,HDFC Bank,HDFCBANK,Financial Services,22 April 1996
18,HDFC Life,HDFCLIFE,Financial Services,31 July 2020
19,Hindalco Industries,HINDALCO,Metals & Mining,22 April 1996
20,Hindustan Unilever,HINDUNILVR,Fast Moving Consumer Goods,22 April 1996
21,ICICI Bank,ICICIBANK,Financial Services,25 January 2002
22,IndiGo,INDIGO,Services,30 September 2025
23,Infosys,INFY,Information Technology,7 October 1998
24,ITC,ITC,Fast Moving Consumer Goods,22 April 1996
25,Jio Financial Services,JIOFIN,Financial Services,28 March 2025
26,JSW Steel,JSWSTEEL,Metals & Mining,28 September 2018
27,Kotak Mahindra Bank,KOTAKBANK,Financial Services,8 April 2010
28,Larsen & Toubro,LT,Construction,10 December 2004[e]
29,Mahindra & Mahindra,M&M,Automobile and Auto Components,18 September 1996
30,Maruti Suzuki,MARUTI,Automobile and Auto Components,1 March 2004
31,Max Healthcare,MAXHEALTH,Healthcare,30 September 2025
32,Nestlé India,NESTLEIND,Fast Moving Consumer Goods,27 September 2019[f]
33,NTPC,NTPC,Power,24 September 2007
34,Oil and Natural Gas Corporation,ONGC,"Oil, Gas & Consumable Fuels",12 April 2004
35,Power Grid,POWERGRID,Power,14 March 2008
36,Reliance Industries,RELIANCE,"Oil, Gas & Consumable Fuels",22 April 1996
37,SBI Life Insurance Company,SBILIFE,Financial Services,25 September 2020
38,Shriram Finance,SHRIRAMFIN,Financial Services,28 March 2024
39,State Bank of India,SBIN,Financial Services,22 April 1996
40,Sun Pharma,SUNPHARMA,Healthcare,17 January 2002
41,Tata Consultancy Services,TCS,Information Technology,25 February 2005
42,Tata Consumer Products,TATACONSUM,Fast Moving Consumer Goods,31 March 2021[g]
43,Tata Motors Passenger Vehicles,TMPV,Automobile and Auto Components,22 April 1996
44,Tata Steel,TATASTEEL,Metals & Mining,22 April 1996
45,Tech Mahindra,TECHM,Information Technology,28 March 2014
46,Titan Company,TITAN,Consumer Durables,2 April 2018
47,Trent,TRENT,Consumer Services,30 September 2024
48,UltraTech Cement,ULTRACEMCO,Construction Materials,28 September 2012
49,Wipro,WIPRO,Information Technology,27 September 2013[h]

In [3]:
l1=[]
for i in df['Date added[16]']:
    if i[-3]=='[':
        l1.append(i[:-3])
    else:
        l1.append(i)
l1
df['Date added[16]']=l1

In [12]:
a='30 September 2022'
b=pd.to_datetime(a,format='%d %B %Y')
b.year

2022

In [9]:
df['Date added[16]']=pd.to_datetime(df['Date added[16]'])

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Company name    50 non-null     str
 1   Symbol          50 non-null     str
 2   Sector[15]      50 non-null     str
 3   Date added[16]  50 non-null     datetime64[us]
dtypes: datetime64[us](1), str(3)
memory usage: 1.7 KB

In [16]:
df[df['Date added[16]'].dt.year>2023]

              Company name      Symbol          Sector[15] Date added[16]
8       Bharat Electronics         BEL       Capital Goods     2024-09-30
14                 Eternal     ETERNAL   Consumer Services     2025-03-28
22                  IndiGo      INDIGO            Services     2025-09-30
25  Jio Financial Services      JIOFIN  Financial Services     2025-03-28
31          Max Healthcare   MAXHEALTH          Healthcare     2025-09-30
38         Shriram Finance  SHRIRAMFIN  Financial Services     2024-03-28
47                   Trent       TRENT   Consumer Services     2024-09-30